/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { ServerRoute as ApiTiktokChatServerRouteImport } from './routes/api/tiktok-chat'
import { ServerRoute as ApiJobServerRouteImport } from './routes/api/job'

const rootServerRouteImport = createServerRootRoute()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTiktokChatServerRoute = ApiTiktokChatServerRouteImport.update({
  id: '/api/tiktok-chat',
  path: '/api/tiktok-chat',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiJobServerRoute = ApiJobServerRouteImport.update({
  id: '/api/job',
  path: '/api/job',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
}
export interface FileServerRoutesByFullPath {
  '/api/job': typeof ApiJobServerRoute
  '/api/tiktok-chat': typeof ApiTiktokChatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/job': typeof ApiJobServerRoute
  '/api/tiktok-chat': typeof ApiTiktokChatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/job': typeof ApiJobServerRoute
  '/api/tiktok-chat': typeof ApiTiktokChatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/job' | '/api/tiktok-chat'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/job' | '/api/tiktok-chat'
  id: '__root__' | '/api/job' | '/api/tiktok-chat'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiJobServerRoute: typeof ApiJobServerRoute
  ApiTiktokChatServerRoute: typeof ApiTiktokChatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/tiktok-chat': {
      id: '/api/tiktok-chat'
      path: '/api/tiktok-chat'
      fullPath: '/api/tiktok-chat'
      preLoaderRoute: typeof ApiTiktokChatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/job': {
      id: '/api/job'
      path: '/api/job'
      fullPath: '/api/job'
      preLoaderRoute: typeof ApiJobServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiJobServerRoute: ApiJobServerRoute,
  ApiTiktokChatServerRoute: ApiTiktokChatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
